# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/index.html

In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::StridedArray{T, 2}) where T in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1207
[2] factorize(A::Adjoint) in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1283
[3] factorize(A::Transpose) in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1284
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\triangular.jl:2676
[5] factorize(A::Union{Hermitian{Complex{Float64},var"#s828"}, Hermitian{Float64,var"#s828"}, Symmetric{Float64,var"#s828"}} where var"#s828"<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1538
[6] factorize(A::Union{Hermitian{T,S}, Symmetric{T,S}} where S where T) in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\symmetric.jl:634
[7] factorize(A::Tridiagonal) in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\lu.jl:555
[8] factorize(D::Diagonal) in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\diagonal.jl:121
[9] factorize(A::Bidiagonal) in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\bidiag.jl:875
[10] factorize(S::SymTridiagonal) in LinearAlgebra at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\ldlt.jl:166
[11] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\sylwi\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1508

In [3]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [4]:
y1=[1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [5]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [6]:
#iloczyn skalarny
dot(x1,y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [7]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Array{Float64,2}:
 0.565936   0.300095  0.00172226
 0.0766113  0.488387  0.149067
 0.364564   0.225734  0.770428

In [8]:
#losujemy wektor x
x=rand(3)

3-element Array{Float64,1}:
 0.8870913489238519
 0.26124660107879594
 0.9173661470271073

In [9]:
# wyliczamy b
b=A*x

3-element Array{Float64,1}:
 0.5820156081609066
 0.3323001953791924
 1.089138591836072

### Sposoby rozwiązania Ax=b

In [10]:
#mozemy policzyc odwrotność macierzy i wymnożyć
#uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.8870913489238518
 0.261246601078796
 0.9173661470271074

In [11]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Array{Float64,1}:
 0.8870913489238518
 0.261246601078796
 0.9173661470271075

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


### Faktoryzacja LU

In [12]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0        0.0
 0.135371  1.0        0.0
 0.64418   0.0724013  1.0
U factor:
3×3 Array{Float64,2}:
 0.565936  0.300095  0.00172226
 0.0       0.447763  0.148834
 0.0       0.0       0.758543

In [13]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0       0.0        0.0
 0.135371  1.0        0.0
 0.64418   0.0724013  1.0

In [14]:
#Macierz U
Af.U

3×3 Array{Float64,2}:
 0.565936  0.300095  0.00172226
 0.0       0.447763  0.148834
 0.0       0.0       0.758543

In [15]:
# wektor permutacji wierszy 
Af.p

3-element Array{Int64,1}:
 1
 2
 3

In [16]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0       0.0        0.0
 0.135371  1.0        0.0
 0.64418   0.0724013  1.0
U factor:
3×3 Array{Float64,2}:
 0.565936  0.300095  0.00172226
 0.0       0.447763  0.148834
 0.0       0.0       0.758543

In [17]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.8870913489238518
 0.261246601078796
 0.9173661470271075

In [18]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Array{Float64,1}:
 -0.5601436931096339
  1.5191708928945309
  0.4273529746320426

### Faktoryzacja QR


In [19]:
B=rand(10,5)

10×5 Array{Float64,2}:
 0.487816   0.343795   0.312645   0.906513  0.342731
 0.0671475  0.26938    0.664036   0.183178  0.0450427
 0.884488   0.0149139  0.747245   0.167878  0.947538
 0.699025   0.996289   0.798687   0.733003  0.335665
 0.350462   0.110614   0.960855   0.166565  0.421037
 0.596881   0.0843095  0.998431   0.432924  0.758062
 0.396232   0.1664     0.0680702  0.903408  0.579591
 0.615443   0.0326784  0.559247   0.924661  0.443435
 0.263517   0.0709799  0.520381   0.743365  0.421093
 0.773755   0.521304   0.79689    0.277798  0.967744

In [20]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.141553    0.484017   0.0631977  …  -0.719128   -0.289376    0.154581
 -0.300648   -0.141583   0.429959      -0.120818    0.110327    0.159551
 -0.338321   -0.185006  -0.519702      -0.174156    0.291237   -0.34991
 -0.361612    0.173889   0.340916       0.15104     0.150863   -0.296393
 -0.435035   -0.270992   0.201924       0.201244   -0.493521   -0.326037
 -0.452047   -0.107145  -0.0765447  …  -0.264848   -0.134611    0.0450458
 -0.0308193   0.579373  -0.358884       0.23979    -0.27192    -0.37758
 -0.253203    0.397951   0.116662       0.472562   -0.0254096   0.414319
 -0.235607    0.291725   0.0682187     -0.0293753   0.677222   -0.0750133
 -0.360798   -0.130991  -0.480763       0.150979   -0.0401536   0.55873
R factor:
5×5 Array{Float64,2}:
 -2.20869  -1.31075  -1.60837   -0.799413  -1.57284
  0.0       1.48956   0.355601   0.321571   0.475598
  0.0       0.0      -0.902789 

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [21]:
A=zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [22]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [23]:
A[:,1]=x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [24]:
A[:,2]=x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [25]:
A[:,3]=ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [27]:
 AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788
   0.0    -2.34816  -1.43091
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

In [28]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           1.11022e-16  …   8.32667e-17   0.0
  0.0           1.0           9.71445e-17     -5.55112e-17  -1.249e-16
  1.11022e-16   9.71445e-17   1.0             -4.16334e-17   0.0
 -9.71445e-17   3.46945e-17   2.60209e-17     -9.88792e-17  -2.08167e-17
  8.32667e-17  -5.55112e-17  -4.16334e-17      1.0           0.0
  0.0          -1.249e-16     0.0          …   0.0           1.0

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [29]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285725
  3.9428571428571515
 -2.8000000000000163

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [30]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285726
  3.942857142857151
 -2.8000000000000145

In [31]:
#sprawdzamy czy dostaliśmy dobre współczynniki
using Polynomials
fit(x,y, 2)

Polynomial(-2.8 + 3.9428571428571417*x - 0.5714285714285711*x^2)

In [32]:
@which fit

Polynomials

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/master/src/common.jl#L142">
fit</a>  z pakietu Polynomials używa własnie tej metody


### Zadania

#### Zadanie 1 (1pkt)
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3 (2 pkt)

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254




## Zad 1.

In [33]:
A = rand(1000,1000)

1000×1000 Array{Float64,2}:
 0.083294   0.617632    0.944548    …  0.830245  0.0488413  0.989938
 0.257234   0.0237225   0.1777         0.751845  0.127206   0.0103696
 0.407145   0.992247    0.560034       0.441706  0.965907   0.494085
 0.201782   0.189819    0.816871       0.188394  0.207522   0.509339
 0.9084     0.00638772  0.263995       0.857943  0.5271     0.938044
 0.253842   0.805761    0.641803    …  0.662608  0.430011   0.426338
 0.0156398  0.685418    0.823024       0.925031  0.580355   0.530805
 0.0142553  0.242992    0.571203       0.881923  0.772944   0.0270614
 0.471706   0.671394    0.818199       0.164838  0.151561   0.530101
 0.299181   0.780179    0.542065       0.561579  0.149826   0.609578
 0.689117   0.105427    0.248772    …  0.457921  0.647267   0.322066
 0.0849191  0.757639    0.0472726      0.355325  0.744914   0.411827
 0.681094   0.264835    0.369256       0.693933  0.557482   0.196894
 ⋮                                  ⋱                       
 0.399969   

In [34]:
x = rand(1000)

1000-element Array{Float64,1}:
 0.7777679797328616
 0.48088902853302873
 0.8909080479166267
 0.8382812479987813
 0.5946533327450354
 0.41374589920557314
 0.1387045685462458
 0.6477305464982752
 0.6099490525864166
 0.5064772073739952
 0.9163979480964695
 0.36758155284603133
 0.5549082952870064
 ⋮
 0.312703810086576
 0.0741322478700761
 0.7108961777203275
 0.6052323454703319
 0.9133932196187169
 0.57038521340729
 0.8232166979940994
 0.6274797033623498
 0.7364640118133305
 0.2125580543702288
 0.8952208339291952
 0.8094716611391883

In [35]:
b = A*x

1000-element Array{Float64,1}:
 242.21604489031813
 244.72170157395587
 254.6454059740323
 251.70931892541736
 246.4119300909217
 249.745506045543
 249.28044378779123
 237.95506215057787
 251.53441988724833
 253.38585418855075
 261.1553670158279
 251.10946954104304
 244.9612369127479
   ⋮
 245.1169700740595
 253.08899410996094
 249.43325685996382
 245.73255281650958
 247.7344906513948
 253.06006737561785
 255.2922119049028
 251.0041109576564
 244.05749727005502
 249.56423383437902
 252.64391514346715
 258.3517290409023

In [36]:
# initial compilation 
inv(A) * b
A\b
Af = factorize(A)
Af\b


# time measure
time_inv = time_div = time_fac = 0
x1 = []
x2 = []
x3 = []

for i in 1:10
    time_inv += @elapsed x1 = inv(A) * b
    time_div += @elapsed x2 = A\b
    time_fac += @elapsed Af = factorize(A); x3 = Af\b
end

time_inv /= 10
time_div /= 10
time_fac /= 10

println("inv() time:        ",  round(time_inv, digits=10))
println("\\ time:            ", round(time_div, digits=10))
println("factorize() time:  ",  round(time_fac, digits=10))

inv() time:        0.0746334897
\ time:            0.0278131404
factorize() time:  0.0275442304


In [37]:
q1 = sqrt(dot(x-x1,x-x1))
q2 = sqrt(dot(x-x2,x-x2))
q3 = sqrt(dot(x-x3,x-x3))

println("inv() quality:        ",  q1)
println("\\ quality:            ", q2)
println("factorize() quality:  ",  q3)

inv() quality:        4.138099214374059e-10
\ quality:            2.0230510305378292e-10
factorize() quality:  2.0230510305378292e-10


## Zad 2.
Wykorzystałam dane z lab2 (mnożenie macierzy kwadratowej przez wektor - $O(N^2)$.

In [38]:
using CSV
using DataFrames
using Statistics

In [39]:
res = CSV.read("results.csv", DataFrame)

390×4 DataFrame
 Row │ size   i      time       type   
     │ Int64  Int64  Float64    String 
─────┼─────────────────────────────────
   1 │   600      1  3.99e-7    v
   2 │   600      2  4.99e-7    v
   3 │   600      3  4.0e-7     v
   4 │   600      4  4.0e-7     v
   5 │   600      5  5.0e-7     v
   6 │   600      6  5.0e-7     v
   7 │   600      7  4.99e-7    v
   8 │   600      8  5.0e-7     v
   9 │   600      9  5.01e-7    v
  10 │   600     10  4.99e-7    v
  11 │   600      1  0.0012846  m
  ⋮  │   ⋮      ⋮        ⋮        ⋮
 381 │  3100      1  2.0e-6     v
 382 │  3100      2  2.301e-6   v
 383 │  3100      3  1.999e-6   v
 384 │  3100      4  1.999e-6   v
 385 │  3100      5  2.0e-6     v
 386 │  3100      6  1.9e-6     v
 387 │  3100      7  2.0e-6     v
 388 │  3100      8  2.101e-6   v
 389 │  3100      9  2.001e-6   v
 390 │  3100     10  2.2e-6     v
                       369 rows omitted

In [62]:
res_m = res[res[!,:type] .== "m", :]
res_grouped = combine(groupby(res_m, :size), "time" => mean)

13×2 DataFrame
 Row │ size   time_mean  
     │ Int64  Float64    
─────┼───────────────────
   1 │   600  0.00351529
   2 │   800  0.00247528
   3 │  1000  0.00491061
   4 │  1200  0.0075149
   5 │  1400  0.00800567
   6 │  1600  0.0150469
   7 │  1800  0.021611
   8 │  2000  0.0256406
   9 │  2200  0.0320328
  10 │  2400  0.0457893
  11 │  2600  0.0586774
  12 │  2800  0.0698941
  13 │  3000  0.0841519

#### Dopasowanie do danych wielomianu przy użyciu funcji ```fit()``` z pakietu Polynomials

In [41]:
x = res_grouped[!, :size]
y = res_grouped[!, :time_mean]

fit(x,y,2)

Polynomial(0.01466387135334673 - 2.762089318581425e-5*x + 1.690210814685316e-8*x^2)

#### Dopasowanie do danych wielomianu tworząc wprost układ równań i rozwiązujac go

In [42]:
A = zeros(length(x),3)
A[:,1] = x.^2
A[:,2] = x
A[:,3] = ones(length(x))

A

13×3 Array{Float64,2}:
 360000.0      600.0  1.0
 640000.0      800.0  1.0
      1.0e6   1000.0  1.0
      1.44e6  1200.0  1.0
      1.96e6  1400.0  1.0
      2.56e6  1600.0  1.0
      3.24e6  1800.0  1.0
      4.0e6   2000.0  1.0
      4.84e6  2200.0  1.0
      5.76e6  2400.0  1.0
      6.76e6  2600.0  1.0
      7.84e6  2800.0  1.0
      9.0e6   3000.0  1.0

In [43]:
coef = A\y

3-element Array{Float64,1}:
  1.690210814685312e-8
 -2.7620893185814095e-5
  0.01466387135334658

In [44]:
Polynomial(reverse(coef))

Polynomial(0.01466387135334658 - 2.7620893185814095e-5*x + 1.690210814685312e-8*x^2)

### Wnioski:
Wielomiany otrzymane przy użyciu obydwu metod są do siebie bardzo zbliżone, współczynniki różnią się w okolicy 16 miejsca po przecinku.

## Zad 3.
### Użycie faktoryzacji QR do znajdowania wektorów i wartości własnych

* https://en.wikipedia.org/wiki/QR_algorithm
* https://duch.mimuw.edu.pl/~m_korch/pl/12-eigenvalues-and-eigenvectors/
* http://matrix.umcs.lublin.pl/~lbocian/Studia/Pracownia_obliczen_numerycznych_II/algorytm_qr.htm
* https://people.inf.ethz.ch/arbenz/ewp/Lnotes/chapter4.pdf

### Wstęp:
$v$ - wektor własny przekształcenia (wektor, którego kierunek nie ulega zmianie po przekształceniu go endomorfizmem)

$\lambda$ - wartość własna przekształcenia $\varphi$ (skala podobieństwa tych wektorów)

Spełniają one następujący warunek:
$$ \varphi(v)=\lambda v $$


W ogólności, aby znaleźć wartości własne przekształcenia, należy rozwiązać równanie:

$$ \det (M-\lambda I)=0, $$
gdzie $M$ jest macierzą przekształcenia $\varphi$.

Gdy znamy już wartości własne, jesteśmy w stanie wyliczyc odpowiadające im wektory własne, rozwiązując odpowiednie równania.

### Algorytm:
Do wyznaczenia wartości i wektorów własnych możemy wykorzystać faktoryzację $QR$.

Niech dana jest macierz $M$ (symetryczna), mająca rozkład $QR$ postaci $M = QR$, gdzie gdzie $Q$ jest macierzą ortogonalną $(Q^{T}Q=I)$ i $R$ jest macierzą trójkątną górną. Tworzymy macierz $Q product$, która będzie wykorzystywana do odczytania wektorów własnych (początkowo jest to macierz jednostkowa, inaczej identycznościowa).

* przyjmijmy za początkową wartość $M_1 = M$
* dla każdego $M_k$ dokonujemy rozkładu $QR$ ($M_k = Q_k R_k$) 
* i przyjmujemy, że $M_{k+1} = R_k Q_k$

Wówczas dla dostatecznie dużej liczby iteracji macierze $M_k$ zbiegają to pewnej macierzy górnej trójkatnej $D$, na jej głównej przekątnej leżą wartości własne przekształcenia. Wektory własne znajdują sie w kolumnach macierzy $Q product = \Pi_i Q_i$, będącej iloczynem wyliczanych kolejno macierzy ortogonalnych $Q_i$.

### Przykład 1.

In [45]:
M1 = [52.0 30.0 49.0 28.0;
     30.0 50.0 8.0 44.0;
     49.0 8.0 46.0 16.0;
     28.0 44.0 16.0 22.0]

4×4 Array{Float64,2}:
 52.0  30.0  49.0  28.0
 30.0  50.0   8.0  44.0
 49.0   8.0  46.0  16.0
 28.0  44.0  16.0  22.0

#### Przy użyciu funkcji bibliotecznych:

In [46]:
eigen(M1).values

4-element Array{Float64,1}:
 -11.541130784673527
  -3.529044547945997
  52.44229999841107
 132.62787533420826

In [47]:
eigen(M1).vectors

4×4 Array{Float64,2}:
  0.0998774   0.727071   0.299919  -0.60946
 -0.577249   -0.06069   -0.651997  -0.487853
 -0.221563   -0.60898    0.601962  -0.466578
  0.779562   -0.311173  -0.350128  -0.415769

#### Przy użyciu faktoryzacji QR:

In [48]:
function eigen_own(M)
    Mk = M
    Q_product = Array{Float64}(I,size(M)[1],size(M)[1])   # identity matrix

    for i in 1:500
        Q, R = qr(Mk)
        Q_product *= Q
        Mk = R*Q
    end
    
    eigen_values = diag(Mk)
    eigen_vectors = round.(Q_product, digits=6)
    return eigen_values, eigen_vectors
end

eigen_own (generic function with 1 method)

In [49]:
eigen_values = eigen_own(M1)[1]

4-element Array{Float64,1}:
 132.62787533420854
  52.44229999841114
 -11.541130784673536
  -3.5290445479460026

In [50]:
eigen_vectors = eigen_own(M1)[2]

4×4 Array{Float64,2}:
 0.60946    0.299919  -0.099877  -0.727071
 0.487853  -0.651997   0.577249   0.06069
 0.466578   0.601962   0.221563   0.60898
 0.415769  -0.350128  -0.779562   0.311173

### Przykład 2.

In [51]:
M2 = [1.0 2.0 1.0;
      2.0 14.0 5.0;
      1.0 5.0 8.0]

3×3 Array{Float64,2}:
 1.0   2.0  1.0
 2.0  14.0  5.0
 1.0   5.0  8.0

#### Wartości własne

In [52]:
eigen(M2).values

3-element Array{Float64,1}:
  0.6881254087357362
  5.171933220863287
 17.139941370400983

In [53]:
eigen_own(M2)[1]

3-element Array{Float64,1}:
 17.13994137040098
  5.171933220863286
  0.6881254087357356

In [54]:
eigen(M2).values

3-element Array{Float64,1}:
  0.6881254087357362
  5.171933220863287
 17.139941370400983

#### Wektory własne

In [55]:
eigen(M2).vectors

3×3 Array{Float64,2}:
  0.990246   -0.0250368  -0.137062
 -0.131747   -0.488366   -0.862636
 -0.0453388   0.87228    -0.486901

In [56]:
eigen_own(M2)[2]

3×3 Array{Float64,2}:
 0.137062   0.025037  -0.990246
 0.862636   0.488366   0.131747
 0.486901  -0.87228    0.045339

### Przykład 3. 
Losowa macierz (symetryczna)

In [57]:
M3 = Symmetric(rand(7,7))

7×7 Symmetric{Float64,Array{Float64,2}}:
 0.386441  0.765316   0.178615   0.839148  0.23297   0.734343   0.349815
 0.765316  0.0971688  0.844735   0.604433  0.307829  0.976312   0.13269
 0.178615  0.844735   0.0552335  0.786777  0.608066  0.0511545  0.248499
 0.839148  0.604433   0.786777   0.237771  0.915904  0.939517   0.571161
 0.23297   0.307829   0.608066   0.915904  0.132652  0.300375   0.794191
 0.734343  0.976312   0.0511545  0.939517  0.300375  0.882472   0.969728
 0.349815  0.13269    0.248499   0.571161  0.794191  0.969728   0.358194

#### Wartości własne

In [58]:
eigen(M3).values

7-element Array{Float64,1}:
 -1.3384273425223516
 -0.8573390419361162
 -0.6119895417292647
 -0.1647199967050328
  0.5268573616813899
  0.6750229198877316
  3.9205283792463588

In [59]:
eigen_own(M3)[1]

7-element Array{Float64,1}:
  3.9205283792463708
 -1.338427342522353
 -0.8573390419361138
  0.6750229198877364
 -0.611989541729266
  0.5268573616813919
 -0.16471999670503223

#### Wektory własne

In [60]:
eigen(M3).vectors

7×7 Array{Float64,2}:
  0.243239   0.0222288   0.307522  …   0.356257   0.250366   -0.357744
 -0.518891   0.384347    0.262339      0.488481   0.0226082  -0.365435
  0.468806  -0.400014    0.234833      0.271378  -0.567141   -0.267519
 -0.427255  -0.40796    -0.586247      0.031785  -0.207942   -0.455802
  0.199376   0.683715   -0.161026     -0.334741  -0.480672   -0.315982
  0.403455   0.0224619  -0.29831   …  -0.123844   0.58223    -0.490563
 -0.25833   -0.23952     0.568206     -0.657588   0.0433616  -0.344468

In [61]:
eigen_own(M3)[2]

7×7 Array{Float64,2}:
 0.357744  -0.243239   0.022229  -0.250366  -0.307522   0.356257  -0.726766
 0.365435   0.518891   0.384347  -0.022608  -0.262339   0.488481   0.376217
 0.267519  -0.468806  -0.400014   0.567141  -0.234833   0.271378   0.313371
 0.455802   0.427255  -0.40796    0.207942   0.586247   0.031785  -0.235227
 0.315982  -0.199376   0.683715   0.480672   0.161026  -0.334741  -0.154633
 0.490563  -0.403455   0.022462  -0.58223    0.29831   -0.123844   0.390833
 0.344468   0.25833   -0.23952   -0.043362  -0.568206  -0.657588   0.008797

### Obserwacje:
Jak widzimy w powyżej przedstawionych przykładach, wartości i wektory własne wyliczone przy użyciu faktoryzacji $QR$ są takie same, jak te otrzymane wykorzystując wbudowaną funkcję ```eigen()``` (z odpowiednią dokładnością).